// JogaTime — expanded bilingual content (30 practices, 30 affirmations, 12 leyes)
// Contenido bilingüe expandido para JogaTime (dominio del tiempo, productividad, enfoque)
window.JOGA_CONTENT_JOGATIME = {
es: {
  practices: [
    // === Original 3 (índice 0-2) ===
    {icon:'🗓️', num:'Práctica 01', title:'Bloquea tu hora más importante', desc:'Antes de abrir nada más, reserva un bloque para tu tarea número uno del día.', extra:'Elige UNA tarea que mueva la aguja · dale una hora fija en tu calendario · protégela como una cita inamovible.'},
    {icon:'🎯', num:'Práctica 02', title:'Una sola cosa a la vez', desc:'Trabaja 25 minutos en una única tarea, sin pestañas ni notificaciones.', extra:'Cierra todo lo demás · pon el teléfono lejos · si llega una distracción, anótala y vuelve. El foco es un músculo.'},
    {icon:'🌅', num:'Práctica 03', title:'Cierra el día en 3 líneas', desc:'Antes de terminar, escribe qué lograste y cuál es tu primera tarea de mañana.', extra:'¿Qué avancé hoy? · ¿qué me robó tiempo? · ¿cuál es mi bloque #1 de mañana? Así empiezas el día ya decidido.'},
    // === 27 nuevas prácticas (índice 3-29) ===
    {icon:'🧱', num:'Práctica 04', title:'Bloqueo de tiempo por colores', desc:'Asigna colores a tipos de tarea en tu calendario: creativo, admin, reuniones, descanso.', extra:'Abre tu calendario · crea 4 categorías con colores · bloquea la semana entera el domingo · si un color domina demasiado, reequilibra. Visualizar tu tiempo revela dónde se va.'},
    {icon:'🔬', num:'Práctica 05', title:'Sesión de trabajo profundo', desc:'Reserva 90 minutos sin interrupciones para tu proyecto más exigente.', extra:'Pon el teléfono en modo avión · cierra email y chat · coloca un cartel de "no molestar" · trabaja en UNA sola entrega · al terminar, prémiate con 15 min libres. 90 minutos de foco = 4 horas fragmentadas.'},
    {icon:'🍅', num:'Práctica 06', title:'Pomodoro Adaptado', desc:'Trabaja 25 min, descansa 5. Cada 4 ciclos, pausa larga de 20 min.', extra:'Usa un timer visible · anota la tarea antes de cada pomodoro · si te distraes, marca una X y vuelve · después de 4 ciclos revisa: ¿avanzaste lo que importa? Ajusta la duración a tu ritmo (25/50/90 min).'},
    {icon:'🔍', num:'Práctica 07', title:'Auditoría de distracciones', desc:'Durante un día entero, anota cada vez que algo te saque de tu tarea.', extra:'Lleva una hoja dividida en 3 columnas: hora, distracción, duración · al final del día cuenta: ¿cuántos minutos perdiste? · identifica el top 3 de ladrones · crea una regla para cada uno. Lo que mides, mejora.'},
    {icon:'⚡', num:'Práctica 08', title:'Mapeo de energía', desc:'Registra tu nivel de energía cada hora durante 3 días para encontrar tus picos.', extra:'Cada hora puntúa tu energía de 1 a 5 · después de 3 días, busca el patrón · pon las tareas difíciles en tus picos · deja admin y emails para los valles. Tu mejor hora vale oro: no la desperdicies en lo trivial.'},
    {icon:'📋', num:'Práctica 09', title:'Revisión semanal', desc:'Cada viernes, revisa qué funcionó, qué no, y planifica la siguiente semana.', extra:'Dedica 30 min el viernes · revisa tus 3 metas de la semana: ¿las lograste? · anota 1 victoria y 1 lección · define tus 3 prioridades de la próxima semana · bloquea sus horarios. Quien revisa, no repite errores.'},
    {icon:'☀️', num:'Práctica 10', title:'Rutina matutina de 30 min', desc:'Los primeros 30 minutos definen el día. Diseña una secuencia que te active.', extra:'Levántate y NO toques el teléfono · 5 min de movimiento · 5 min de intención (escribe tu meta #1) · 10 min de la tarea más importante · 10 min de lectura o aprendizaje. Gana la mañana y ganas el día.'},
    {icon:'🌙', num:'Práctica 11', title:'Apagado nocturno', desc:'A las 9 PM cierra loops: revisa el día, prepara mañana y desconecta pantallas.', extra:'Escribe 3 cosas que lograste · define tu tarea #1 de mañana · deja la ropa lista · pon el teléfono fuera del cuarto · lee 10 min en papel. El cierre consciente = un amanecer con claridad.'},
    {icon:'📦', num:'Práctica 12', title:'Procesamiento por lotes', desc:'Agrupa tareas similares y hazlas todas juntas en un solo bloque.', extra:'Emails: un bloque a las 10 y otro a las 4 · llamadas: todas entre 2 y 3 · compras: una vez por semana · el cambio de contexto cuesta 23 minutos de re-enfoque. Agrupa y elimina ese costo.'},
    {icon:'⏱️', num:'Práctica 13', title:'Regla de los 2 minutos', desc:'Si una tarea toma menos de 2 minutos, hazla ahora mismo. No la pospongas.', extra:'Revisa tu lista de pendientes · si algo se puede hacer en 2 min o menos, hazlo ya · responde ese mensaje, archiva ese documento, confirma esa cita · lo pequeño acumulado se vuelve una montaña. Despeja rápido y libera espacio mental.'},
    {icon:'🏛️', num:'Práctica 14', title:'Ejercicio de matriz Eisenhower', desc:'Clasifica todas tus tareas en 4 cuadrantes: urgente/importante, importante/no urgente, urgente/no importante, ni urgente ni importante.', extra:'Dibuja una cruz en una hoja · arriba izquierda: urgente + importante (hazlo ya) · arriba derecha: importante no urgente (agéndalo) · abajo izquierda: urgente no importante (delega) · abajo derecha: ni urgente ni importante (elimina). Hazlo cada lunes.'},
    {icon:'📓', num:'Práctica 15', title:'Diario de tiempo', desc:'Durante una semana, registra en qué gastas cada bloque de 30 minutos.', extra:'Usa una libreta o app simple · cada 30 min anota qué hiciste · al final de la semana suma: ¿cuántas horas fueron productivas vs. desperdiciadas? · el shock de ver los números reales cambia tu comportamiento para siempre.'},
    {icon:'🧠', num:'Práctica 16', title:'Entrenamiento de atención', desc:'Practica 10 minutos de foco en un solo objeto sin dejar que tu mente divague.', extra:'Elige un objeto (una vela, tu respiración, un punto en la pared) · mira/siente solo eso durante 10 min · cada vez que tu mente se vaya, tráela de vuelta sin juzgarte · cuenta las veces que divagaste. Semana a semana el número baja y tu foco sube.'},
    {icon:'📵', num:'Práctica 17', title:'Desintoxicación digital', desc:'Elige 2 horas al día donde no tocas el teléfono ni redes sociales.', extra:'Pon el teléfono en otra habitación · desactiva notificaciones no esenciales · usa esas 2 horas para trabajo profundo, lectura o conversación real · anota cómo te sientes después. El cerebro necesita silencio digital para pensar con claridad.'},
    {icon:'🏰', num:'Práctica 18', title:'Horas sagradas', desc:'Declara 2-3 horas al día como intocables. Nadie las mueve, nadie las interrumpe.', extra:'Identifica tu ventana de máxima energía · bloquéala en el calendario como "reunión" · apaga Slack, email y teléfono · trabaja solo en tu proyecto #1 · avisa a tu equipo que en esas horas no estás disponible. Proteger tu foco es un acto de respeto hacia tus metas.'},
    {icon:'🚪', num:'Práctica 19', title:'Rituales de transición', desc:'Entre cada bloque de trabajo, haz una micro-pausa de 2 minutos para resetear.', extra:'Al terminar una tarea: cierra todas las pestañas · respira 3 veces profundo · escribe una línea de lo que lograste · revisa tu siguiente bloque · empieza fresco. Sin transición, arrastras la energía de la tarea anterior a la nueva.'},
    {icon:'🚫', num:'Práctica 20', title:'Bloques libres de reuniones', desc:'Reserva al menos 2 días o medios días por semana sin ninguna reunión.', extra:'Bloquea martes y jueves mañana como "No Meeting Zone" · rechaza o mueve cualquier reunión que caiga ahí · usa esos bloques para trabajo creativo o estratégico · una reunión de 30 min fragmenta 2 horas de foco. Protege tu calendario.'},
    {icon:'📎', num:'Práctica 21', title:'Agrupación de tareas', desc:'Agrupa tareas por tipo y ejecútalas en bloques dedicados.', extra:'Admin: un bloque · correos: 2 bloques cortos · llamadas: un bloque · creativo: bloque largo sin interrupciones · cada cambio de tipo de tarea cuesta re-enfoque. Define "días temáticos" si puedes: lunes = planeación, martes = creación, miércoles = reuniones.'},
    {icon:'🔺', num:'Práctica 22', title:'Pirámide de prioridades', desc:'Cada mañana ordena tus tareas en 3 niveles: una crítica, tres importantes, cinco si-sobra-tiempo.', extra:'Escribe todas tus tareas · pon UNA arriba de la pirámide (la que más impacto tiene) · debajo, 3 importantes · abajo, 5 opcionales · trabaja de arriba hacia abajo · si solo terminas la de arriba, el día fue exitoso. La claridad de prioridad elimina la ansiedad.'},
    {icon:'🏃', num:'Práctica 23', title:'Sprints de enfoque', desc:'Trabaja en ráfagas de 15-20 minutos con intensidad total, luego descansa 3 min.', extra:'Pon un timer de 15 min · elige UNA micro-tarea · trabaja con máxima intensidad · al sonar, para completamente 3 min · repite 4-6 veces · ideal para días de baja motivación o tareas que evitas. La urgencia del timer vence la procrastinación.'},
    {icon:'🌿', num:'Práctica 24', title:'Pausas deliberadas', desc:'Programa descansos reales: caminar, estirarte, mirar por la ventana. Sin pantallas.', extra:'Cada 50-90 min de trabajo, toma 10 min de pausa real · levántate · camina · mira algo lejano (descansa tus ojos) · estírate · NO revises el teléfono · el descanso con pantalla no es descanso. Tu cerebro necesita modo difuso para procesar lo que aprendió.'},
    {icon:'📊', num:'Práctica 25', title:'Auditoría de calendario', desc:'Cada mes, revisa tu calendario de las últimas 4 semanas. ¿Dónde se fue tu tiempo?', extra:'Imprime o revisa tu calendario del mes · clasifica cada evento: ¿fue necesario? ¿productivo? ¿podría haberse eliminado o acortado? · calcula el % de tiempo en reuniones vs. trabajo real · fija un objetivo para el mes siguiente: -20% reuniones. Lo que no auditas, no mejoras.'},
    {icon:'💥', num:'Práctica 26', title:'Rompe-procrastinación', desc:'Cuando evites una tarea, comprométete a solo 5 minutos. La inercia hará el resto.', extra:'Identifica la tarea que estás evitando · di: "solo 5 minutos" · pon un timer · empieza por la parte más pequeña · el 80% de las veces seguirás después de los 5 min · si no, al menos avanzaste algo. La procrastinación es miedo disfrazado: el primer paso la desarma.'},
    {icon:'📥', num:'Práctica 27', title:'Drill de inbox cero', desc:'Vacía tu bandeja de entrada procesando cada mensaje: responder, delegar, archivar o eliminar.', extra:'Abre tu inbox · ve mensaje por mensaje desde arriba · si es de 2 min: responde ya · si requiere acción: ponlo en tu lista de tareas y archívalo · si es info: archívalo · si es basura: bórralo · no dejes nada en la bandeja. Inbox = lista de tareas de otros sobre tu tiempo. Procésala tú.'},
    {icon:'📅', num:'Práctica 28', title:'Planificación del domingo', desc:'Dedica 20 minutos el domingo a diseñar tu semana con intención.', extra:'Revisa tus metas del mes · define 3 resultados clave para la semana · asígnalos a días específicos · bloquea tiempo para ejercicio, descanso y relaciones · anticipa obstáculos y planea soluciones · escribe tu "no haré" de la semana (lo que decides NO hacer es tan importante como lo que decides hacer).'},
    {icon:'🥇', num:'Práctica 29', title:'Top 3 diario', desc:'Cada mañana escribe las 3 únicas cosas que DEBES terminar hoy. No más.', extra:'Antes de revisar email o mensajes · escribe 3 resultados concretos para hoy · ordénalos: el más difícil primero · trabaja solo en esos hasta terminarlos · todo lo demás es bonus. Si haces tus Top 3 todos los días, en un mes habrás avanzado 90 pasos. La consistencia vence al heroísmo.'},
    {icon:'🔒', num:'Práctica 30', title:'Ritual de cierre', desc:'Al terminar de trabajar, haz un ritual que le diga a tu cerebro: "terminamos por hoy."', extra:'Revisa tu lista: ¿qué completaste? · escribe tu tarea #1 de mañana · cierra todas las apps de trabajo · di en voz alta: "el día de trabajo terminó" · el ritual de cierre previene que el trabajo invada tu descanso y te permite recuperar energía para mañana.'},
  ],
  affs: [
    'Soy dueño de mis horas y mi enfoque.',
    'Decido en qué merece vivir mi tiempo.',
    'Una cosa a la vez, hecha bien.',
    'Protejo mi foco como mi bien más valioso.',
    'El tiempo que dirijo es el que de verdad vivo.',
    'Hoy elijo lo importante sobre lo urgente.',
    'Cada hora que protejo es un acto de poder.',
    'Mi atención es mi activo más valioso y la invierto con intención.',
    'No hago más cosas — hago las cosas correctas.',
    'Tengo todo el tiempo que necesito para lo que realmente importa.',
    'Domino mi agenda; mi agenda no me domina.',
    'Cada bloque de tiempo enfocado me acerca a mi mejor versión.',
    'Digo no con facilidad a lo que no merece mi hora.',
    'Mi claridad de prioridades elimina mi ansiedad.',
    'El trabajo profundo es mi superpoder.',
    'Empiezo por lo difícil y el resto fluye solo.',
    'Mis mañanas me pertenecen y las uso con intención.',
    'Cada minuto tiene un propósito y yo lo decido.',
    'Descanso sin culpa porque el descanso recarga mi foco.',
    'Planifico mi semana y la semana me obedece.',
    'Soy imparable cuando elimino las distracciones.',
    'Respeto mi tiempo y por eso otros lo respetan también.',
    'Termino lo que empiezo antes de empezar algo nuevo.',
    'Mi consistencia diaria construye resultados extraordinarios.',
    'Cada día completo mis 3 tareas más importantes.',
    'El tiempo es mi aliado porque lo dirijo con consciencia.',
    'Protejo mis horas sagradas como un guerrero protege su territorio.',
    'Avanzo con calma y propósito, sin prisa pero sin pausa.',
    'Hoy no persigo el tiempo — lo gobierno.',
    'Mi enfoque de hoy construye el éxito de mañana.',
  ],
  leyes: [
    {color:'#d0915e', title:'Ley de Pareto (80/20)', idea:'El 80% de tus resultados viene del 20% de tus tareas. Identifica ese 20% y dale tus mejores horas.', ej:'Antes de empezar, pregúntate: ¿cuál es la tarea que, si solo hago esa, el día ya valió?'},
    {color:'#d0915e', title:'Ley de Parkinson', idea:'El trabajo se expande hasta llenar el tiempo que le das. Ponle un límite más corto y lo terminarás antes.', ej:'Dale a una tarea 45 minutos en vez de «toda la tarde». La urgencia enfoca.'},
    {color:'#c47d44', title:'Ley del bloqueo de tiempo', idea:'Lo que no tiene una hora asignada, no sucede. Reserva bloques en tu calendario, no listas infinitas.', ej:'En vez de «hacer el reporte» en tu lista, ponlo de 10 a 11 en tu agenda.'},
    {color:'#c07b48', title:'Ley del trabajo profundo', idea:'Una hora sin interrupciones vale más que cuatro fragmentadas. Protege bloques de foco total.', ej:'Silencia notificaciones y trabaja una sola cosa 50 minutos seguidos.'},
    {color:'#d49560', title:'Ley de los 2 minutos', idea:'Si algo toma menos de 2 minutos, hazlo ya. Así no se acumula ni te roba atención después.', ej:'Ese correo de una línea: respóndelo ahora, no lo dejes para «luego».'},
    {color:'#d0915e', title:'Ley del descanso intencional', idea:'El foco se agota; el descanso lo recarga. Pausas cortas y reales te hacen más productivo, no menos.', ej:'Cada ~50 minutos, levántate 5: sin pantalla, solo respira o camina.'},
    {color:'#c47d44', title:'Ley del cambio de contexto', idea:'Cada vez que cambias de tarea, tu cerebro tarda 23 minutos en re-enfocarse. Minimiza los cambios.', ej:'Agrupa tareas similares en bloques. No saltes de email a código a llamada a email.'},
    {color:'#c07b48', title:'Ley de la energía finita', idea:'Tu fuerza de voluntad y enfoque se agotan durante el día. Haz lo más difícil cuando tu energía está al máximo.', ej:'Si eres persona de mañanas, pon tu tarea #1 a las 8 AM, no a las 4 PM.'},
    {color:'#d49560', title:'Ley de los rendimientos decrecientes', idea:'Después de cierto punto, más horas no producen más resultados. La calidad del tiempo supera la cantidad.', ej:'Trabaja 6 horas enfocado en vez de 10 horas fragmentadas. El resultado será mejor.'},
    {color:'#d0915e', title:'Ley del primer paso', idea:'La procrastinación se vence con acción, no con motivación. Solo empieza — 5 minutos bastan para romper la inercia.', ej:'¿No quieres escribir el informe? Abre el documento y escribe UNA oración. La inercia hará el resto.'},
    {color:'#c47d44', title:'Ley de la planificación inversa', idea:'Empieza por el resultado final y trabaja hacia atrás. Saber a dónde vas hace cada paso más claro.', ej:'Si necesitas entregar el viernes, ¿qué debe estar listo el jueves? ¿y el miércoles? Planifica desde el deadline.'},
    {color:'#c07b48', title:'Ley del no estratégico', idea:'Cada sí que das a algo sin importancia es un no a algo que importa. Tu tiempo es finito — protégelo con cada decisión.', ej:'Antes de aceptar una reunión o tarea, pregunta: ¿esto me acerca a mi meta #1? Si no, di no o delega.'},
  ],
},
en: {
  practices: [
    // === Original 3 (index 0-2) ===
    {icon:'🗓️', num:'Practice 01', title:'Block your most important hour', desc:'Before opening anything else, reserve a block for your number-one task of the day.', extra:'Pick ONE needle-moving task · give it a fixed hour on your calendar · protect it like an unmovable appointment.'},
    {icon:'🎯', num:'Practice 02', title:'One thing at a time', desc:'Work 25 minutes on a single task, no tabs or notifications.', extra:'Close everything else · put the phone away · if a distraction comes, jot it down and return. Focus is a muscle.'},
    {icon:'🌅', num:'Practice 03', title:'Close the day in 3 lines', desc:'Before you finish, write what you accomplished and your first task for tomorrow.', extra:'What did I move forward today? · what stole my time? · what\'s my #1 block tomorrow? You start the day already decided.'},
    // === 27 new practices (index 3-29) ===
    {icon:'🧱', num:'Practice 04', title:'Color-coded time blocking', desc:'Assign colors to task types in your calendar: creative, admin, meetings, rest.', extra:'Open your calendar · create 4 color-coded categories · block the entire week on Sunday · if one color dominates too much, rebalance. Visualizing your time reveals where it actually goes.'},
    {icon:'🔬', num:'Practice 05', title:'Deep work session', desc:'Reserve 90 uninterrupted minutes for your most demanding project.', extra:'Put your phone on airplane mode · close email and chat · put up a "do not disturb" sign · work on ONE single deliverable · when done, reward yourself with 15 free minutes. 90 focused minutes = 4 fragmented hours.'},
    {icon:'🍅', num:'Practice 06', title:'Adapted Pomodoro', desc:'Work 25 min, rest 5. Every 4 cycles, take a longer 20-min break.', extra:'Use a visible timer · write down the task before each pomodoro · if you get distracted, mark an X and return · after 4 cycles, review: did you advance what matters? Adjust duration to your rhythm (25/50/90 min).'},
    {icon:'🔍', num:'Practice 07', title:'Distraction audit', desc:'For an entire day, write down every time something pulls you from your task.', extra:'Keep a sheet with 3 columns: time, distraction, duration · at the end of the day count: how many minutes did you lose? · identify your top 3 time thieves · create a rule for each one. What you measure, you improve.'},
    {icon:'⚡', num:'Practice 08', title:'Energy mapping', desc:'Log your energy level every hour for 3 days to find your peak performance windows.', extra:'Every hour rate your energy from 1 to 5 · after 3 days, look for the pattern · schedule hard tasks during peaks · leave admin and emails for valleys. Your best hour is gold: don\'t waste it on trivial work.'},
    {icon:'📋', num:'Practice 09', title:'Weekly review', desc:'Every Friday, review what worked, what didn\'t, and plan the next week.', extra:'Dedicate 30 min on Friday · review your 3 weekly goals: did you hit them? · note 1 win and 1 lesson · define your 3 priorities for next week · block their time slots. Those who review don\'t repeat mistakes.'},
    {icon:'☀️', num:'Practice 10', title:'30-minute morning routine', desc:'The first 30 minutes define the day. Design a sequence that activates you.', extra:'Wake up and DO NOT touch your phone · 5 min of movement · 5 min of intention (write your #1 goal) · 10 min on your most important task · 10 min of reading or learning. Win the morning and you win the day.'},
    {icon:'🌙', num:'Practice 11', title:'Evening shutdown', desc:'At 9 PM close all loops: review the day, prepare tomorrow, and disconnect from screens.', extra:'Write 3 things you accomplished · define your #1 task for tomorrow · lay out your clothes · put the phone outside the bedroom · read 10 min on paper. A conscious shutdown = a morning with clarity.'},
    {icon:'📦', num:'Practice 12', title:'Batch processing', desc:'Group similar tasks and do them all together in a single block.', extra:'Emails: one block at 10 and another at 4 · calls: all between 2 and 3 · shopping: once a week · context-switching costs 23 minutes of re-focus. Batch and eliminate that cost.'},
    {icon:'⏱️', num:'Practice 13', title:'The 2-minute rule', desc:'If a task takes less than 2 minutes, do it right now. Don\'t postpone it.', extra:'Review your to-do list · if something can be done in 2 min or less, do it now · reply to that message, file that document, confirm that appointment · small things pile up into mountains. Clear fast and free mental space.'},
    {icon:'🏛️', num:'Practice 14', title:'Eisenhower matrix exercise', desc:'Classify all your tasks into 4 quadrants: urgent/important, important/not urgent, urgent/not important, neither.', extra:'Draw a cross on a sheet · top left: urgent + important (do it now) · top right: important not urgent (schedule it) · bottom left: urgent not important (delegate) · bottom right: neither (eliminate). Do it every Monday.'},
    {icon:'📓', num:'Practice 15', title:'Time journal', desc:'For one week, log what you spend every 30-minute block on.', extra:'Use a notebook or simple app · every 30 min write what you did · at the end of the week tally: how many hours were productive vs. wasted? · the shock of seeing real numbers changes your behavior forever.'},
    {icon:'🧠', num:'Practice 16', title:'Attention training', desc:'Practice 10 minutes of focus on a single object without letting your mind wander.', extra:'Choose an object (a candle, your breath, a point on the wall) · look at/feel only that for 10 min · every time your mind drifts, bring it back without judgment · count how many times you wandered. Week by week the number drops and your focus rises.'},
    {icon:'📵', num:'Practice 17', title:'Digital detox periods', desc:'Choose 2 hours each day where you don\'t touch your phone or social media.', extra:'Put the phone in another room · disable non-essential notifications · use those 2 hours for deep work, reading, or real conversation · note how you feel afterward. The brain needs digital silence to think clearly.'},
    {icon:'🏰', num:'Practice 18', title:'Sacred hours', desc:'Declare 2-3 hours each day as untouchable. No one moves them, no one interrupts them.', extra:'Identify your peak energy window · block it on your calendar as a "meeting" · turn off Slack, email, and phone · work only on your #1 project · tell your team you\'re unavailable during those hours. Protecting your focus is an act of respect toward your goals.'},
    {icon:'🚪', num:'Practice 19', title:'Transition rituals', desc:'Between each work block, take a 2-minute micro-break to reset.', extra:'When you finish a task: close all tabs · take 3 deep breaths · write one line about what you accomplished · check your next block · start fresh. Without transitions, you drag the energy from the previous task into the new one.'},
    {icon:'🚫', num:'Practice 20', title:'Meeting-free blocks', desc:'Reserve at least 2 days or half-days per week with zero meetings.', extra:'Block Tuesday and Thursday mornings as "No Meeting Zone" · decline or move any meeting that lands there · use those blocks for creative or strategic work · a 30-min meeting fragments 2 hours of focus. Protect your calendar.'},
    {icon:'📎', num:'Practice 21', title:'Task batching', desc:'Group tasks by type and execute them in dedicated blocks.', extra:'Admin: one block · emails: 2 short blocks · calls: one block · creative: long uninterrupted block · every task-type switch costs re-focus. Define "theme days" if you can: Monday = planning, Tuesday = creation, Wednesday = meetings.'},
    {icon:'🔺', num:'Practice 22', title:'Priority pyramid', desc:'Each morning, rank your tasks in 3 tiers: one critical, three important, five if-there\'s-time.', extra:'Write all your tasks · put ONE at the top of the pyramid (highest impact) · below it, 3 important ones · at the bottom, 5 optional ones · work top-down · if you only finish the top one, the day was a success. Priority clarity eliminates anxiety.'},
    {icon:'🏃', num:'Practice 23', title:'Focus sprints', desc:'Work in 15-20 minute bursts at full intensity, then rest 3 minutes.', extra:'Set a 15-min timer · pick ONE micro-task · work at maximum intensity · when it rings, stop completely for 3 min · repeat 4-6 times · ideal for low-motivation days or tasks you\'re avoiding. The timer\'s urgency beats procrastination.'},
    {icon:'🌿', num:'Practice 24', title:'Deliberate breaks', desc:'Schedule real breaks: walk, stretch, look out the window. No screens.', extra:'Every 50-90 min of work, take a 10-min real break · stand up · walk · look at something far away (rest your eyes) · stretch · DO NOT check your phone · screen rest is not rest. Your brain needs diffuse mode to process what it learned.'},
    {icon:'📊', num:'Practice 25', title:'Calendar audit', desc:'Each month, review your calendar from the past 4 weeks. Where did your time go?', extra:'Print or review your monthly calendar · classify each event: was it necessary? productive? could it have been eliminated or shortened? · calculate the % of time in meetings vs. real work · set a goal for next month: -20% meetings. What you don\'t audit, you don\'t improve.'},
    {icon:'💥', num:'Practice 26', title:'Procrastination busters', desc:'When you\'re avoiding a task, commit to just 5 minutes. Momentum will do the rest.', extra:'Identify the task you\'re avoiding · say: "just 5 minutes" · set a timer · start with the smallest part · 80% of the time you\'ll keep going after the 5 min · if not, at least you made progress. Procrastination is fear in disguise: the first step disarms it.'},
    {icon:'📥', num:'Practice 27', title:'Inbox zero drill', desc:'Empty your inbox by processing each message: reply, delegate, archive, or delete.', extra:'Open your inbox · go message by message from the top · if it\'s 2 min: reply now · if it requires action: add it to your task list and archive it · if it\'s info: archive it · if it\'s junk: delete it · leave nothing in the inbox. Inbox = other people\'s to-do list for your time. Process it on your terms.'},
    {icon:'📅', num:'Practice 28', title:'Sunday planning', desc:'Spend 20 minutes on Sunday designing your week with intention.', extra:'Review your monthly goals · define 3 key outcomes for the week · assign them to specific days · block time for exercise, rest, and relationships · anticipate obstacles and plan solutions · write your "won\'t do" list for the week (what you choose NOT to do is as important as what you choose to do).'},
    {icon:'🥇', num:'Practice 29', title:'Daily top 3', desc:'Each morning, write the only 3 things you MUST finish today. No more.', extra:'Before checking email or messages · write 3 concrete outcomes for today · order them: hardest first · work only on those until done · everything else is bonus. If you do your Top 3 every day, in a month you\'ll have advanced 90 steps. Consistency beats heroism.'},
    {icon:'🔒', num:'Practice 30', title:'Shutdown ritual', desc:'When you finish working, do a ritual that tells your brain: "we\'re done for today."', extra:'Review your list: what did you complete? · write your #1 task for tomorrow · close all work apps · say out loud: "the workday is over" · the shutdown ritual prevents work from invading your rest and lets you recharge for tomorrow.'},
  ],
  affs: [
    'I own my hours and my focus.',
    'I decide what my time deserves to live in.',
    'One thing at a time, done well.',
    'I protect my focus as my most valuable asset.',
    'The time I steer is the time I truly live.',
    'Today I choose the important over the urgent.',
    'Every hour I protect is an act of power.',
    'My attention is my greatest asset and I invest it with intention.',
    'I don\'t do more things — I do the right things.',
    'I have all the time I need for what truly matters.',
    'I master my schedule; my schedule does not master me.',
    'Every focused time block brings me closer to my best self.',
    'I say no with ease to what doesn\'t deserve my hour.',
    'My clarity of priorities eliminates my anxiety.',
    'Deep work is my superpower.',
    'I start with the hard thing and the rest flows naturally.',
    'My mornings belong to me and I use them with intention.',
    'Every minute has a purpose and I decide what it is.',
    'I rest without guilt because rest recharges my focus.',
    'I plan my week and the week obeys me.',
    'I am unstoppable when I eliminate distractions.',
    'I respect my time and that is why others respect it too.',
    'I finish what I start before starting something new.',
    'My daily consistency builds extraordinary results.',
    'Every day I complete my 3 most important tasks.',
    'Time is my ally because I direct it with awareness.',
    'I guard my sacred hours like a warrior guards territory.',
    'I move with calm and purpose — no rush, but no pause.',
    'Today I don\'t chase time — I govern it.',
    'My focus today builds tomorrow\'s success.',
  ],
  leyes: [
    {color:'#d0915e', title:'Pareto\'s Law (80/20)', idea:'80% of your results come from 20% of your tasks. Find that 20% and give it your best hours.', ej:'Before starting, ask: which task, if it were the only one I did, would make the day worth it?'},
    {color:'#d0915e', title:'Parkinson\'s Law', idea:'Work expands to fill the time you give it. Set a shorter limit and you\'ll finish sooner.', ej:'Give a task 45 minutes instead of "all afternoon." Urgency focuses.'},
    {color:'#c47d44', title:'The time-blocking law', idea:'What has no assigned hour doesn\'t happen. Reserve blocks on your calendar, not endless lists.', ej:'Instead of "do the report" on your list, put it 10–11 on your calendar.'},
    {color:'#c07b48', title:'The deep work law', idea:'One uninterrupted hour is worth more than four fragmented ones. Protect blocks of total focus.', ej:'Mute notifications and work one single thing for 50 minutes straight.'},
    {color:'#d49560', title:'The 2-minute rule', idea:'If something takes less than 2 minutes, do it now. It won\'t pile up or steal your attention later.', ej:'That one-line email: answer it now, don\'t leave it for "later."'},
    {color:'#d0915e', title:'The intentional rest law', idea:'Focus drains; rest recharges it. Short, real breaks make you more productive, not less.', ej:'Every ~50 minutes, get up for 5: no screen, just breathe or walk.'},
    {color:'#c47d44', title:'The context-switching law', idea:'Every time you switch tasks, your brain takes 23 minutes to re-focus. Minimize the switches.', ej:'Batch similar tasks together. Don\'t jump from email to code to calls to email.'},
    {color:'#c07b48', title:'The finite energy law', idea:'Your willpower and focus deplete throughout the day. Do the hardest thing when your energy is at its peak.', ej:'If you\'re a morning person, put your #1 task at 8 AM, not 4 PM.'},
    {color:'#d49560', title:'The law of diminishing returns', idea:'Past a certain point, more hours don\'t produce more results. Quality of time beats quantity.', ej:'Work 6 focused hours instead of 10 fragmented ones. The output will be better.'},
    {color:'#d0915e', title:'The first-step law', idea:'Procrastination is beaten by action, not motivation. Just start — 5 minutes is enough to break inertia.', ej:'Don\'t want to write the report? Open the document and write ONE sentence. Momentum will do the rest.'},
    {color:'#c47d44', title:'The reverse-planning law', idea:'Start from the end result and work backward. Knowing where you\'re going makes every step clearer.', ej:'If you need to deliver on Friday, what must be ready by Thursday? And Wednesday? Plan from the deadline.'},
    {color:'#c07b48', title:'The strategic no', idea:'Every yes you give to something unimportant is a no to something that matters. Your time is finite — protect it with every decision.', ej:'Before accepting a meeting or task, ask: does this move me closer to my #1 goal? If not, say no or delegate.'},
  ],
},
};
