window.JOGA_CONTENT_SUBMENT = {
  es: {
    practices: [
      {icon:'🌅',num:'Práctica 01',title:'La afirmación del día',desc:'Repite hoy una afirmación 5 veces, en voz alta, sintiendo cada palabra.',extra:'Tu afirmación de hoy: «Mi mente trabaja a mi favor. Lo que pienso hoy, lo vivo mañana.»'},
      {icon:'👁️',num:'Práctica 02',title:'La visualización guiada',desc:'Cierra los ojos 5 minutos y vive con detalle la versión de ti que ya logró su sueño.',extra:'Respira hondo 3 veces · imagina una escena específica (dónde, qué vistes, con quién) · siente la emoción de ya haberlo logrado · quédate ahí 5 minutos.'},
      {icon:'📓',num:'Práctica 03',title:'El diario de pensamientos',desc:'Al final del día, escribe 3 pensamientos que tuviste y clasifícalos.',extra:'Pensamiento 1, 2 y 3 → ¿me empujó o me frenó? Lo que repites sin notarlo se vuelve tu realidad.'},
      {icon:'🔍',num:'Práctica 04',title:'Auditoría de creencias',desc:'Identifica 3 creencias que repites sobre ti mismo y evalúa si te sirven.',extra:'Escribe: «Yo soy…», «Yo no puedo…», «La vida es…» → por cada una pregunta: ¿quién me la enseñó? ¿Es verdad absoluta? ¿Me acerca a mi meta? Si no te sirve, reescríbela con una versión que sí.'},
      {icon:'💬',num:'Práctica 05',title:'Reescritura del diálogo interno',desc:'Detecta una frase negativa que te dices hoy y transfórmala en su opuesto constructivo.',extra:'Ejemplo: «No soy suficiente» → «Estoy en constante crecimiento y cada día soy más capaz.» Repite la nueva versión 10 veces en voz alta con convicción. Escríbela en un lugar visible.'},
      {icon:'😨',num:'Práctica 06',title:'Inventario de miedos',desc:'Haz una lista de 5 miedos actuales y pregúntate qué pasaría si no existieran.',extra:'Escribe cada miedo · debajo escribe: «Si este miedo no existiera, yo haría…» · elige uno y haz hoy la acción más pequeña que te acerque a vencerlo. El subconsciente respeta la acción, no la intención.'},
      {icon:'🙏',num:'Práctica 07',title:'Recableado de gratitud',desc:'Escribe 5 cosas por las que estás agradecido como si las acabaras de recibir.',extra:'Usa tiempo presente y emoción: «Estoy profundamente agradecido por…» · cierra los ojos y siente cada una en el cuerpo · la gratitud reprograma el subconsciente hacia la abundancia en menos de 21 días.'},
      {icon:'🎬',num:'Práctica 08',title:'Ensayo mental',desc:'Repasa mentalmente una situación futura viviéndola como si ya tuviera el mejor resultado.',extra:'Elige una reunión, entrevista o conversación próxima · cierra los ojos · vívela paso a paso: qué dices, cómo te mueves, qué sientes · repite 3 veces. Tu cerebro no distingue lo vivido de lo ensayado.'},
      {icon:'🪞',num:'Práctica 09',title:'La técnica del espejo',desc:'Mírate a los ojos en el espejo y repite afirmaciones de identidad durante 3 minutos.',extra:'De pie, mirada directa a tus ojos · repite: «Yo soy poderoso. Yo merezco lo mejor. Mi mente crea mi realidad.» · no rompas el contacto visual · si sientes incomodidad, es señal de que tu subconsciente está procesando el cambio.'},
      {icon:'📝',num:'Práctica 10',title:'Scripting del futuro',desc:'Escribe en presente y con detalle un día completo de tu vida ideal dentro de 3 años.',extra:'Incluye: a qué hora despiertas, dónde vives, qué desayunas, con quién hablas, qué trabajo haces, cuánto ganas, cómo te sientes al dormir · léelo cada noche antes de dormir durante 7 días.'},
      {icon:'🌙',num:'Práctica 11',title:'Programación antes de dormir',desc:'En los últimos 5 minutos antes de dormir, repite una orden clara a tu subconsciente.',extra:'Acostado, relajado, ojos cerrados · repite mentalmente: «Mientras duermo, mi subconsciente trabaja en [tu meta específica]» · visualiza el resultado final · suéltalo y duerme. El estado hipnagógico es la ventana directa al subconsciente.'},
      {icon:'🧘',num:'Práctica 12',title:'Meditación en estado theta',desc:'Medita 10 minutos enfocándote solo en la respiración para alcanzar ondas theta.',extra:'Siéntate cómodo · respira 4-7-8 (inhala 4s, retén 7s, exhala 8s) · no intentes vaciar la mente, solo observa · a los 7-10 minutos entras en theta: aquí tus afirmaciones penetran 100 veces más profundo.'},
      {icon:'🚫',num:'Práctica 13',title:'Eliminación de creencia limitante',desc:'Elige una creencia limitante y aplica el protocolo de 4 pasos para desmontarla.',extra:'1) Escribe la creencia · 2) Busca 3 pruebas de que NO es cierta · 3) Escribe la creencia opuesta empoderada · 4) Repite la nueva creencia 21 días, mañana y noche. El subconsciente acepta lo que se repite con emoción.'},
      {icon:'🦋',num:'Práctica 14',title:'Cambio de identidad',desc:'Define quién necesitas SER (no solo hacer) para lograr tu meta y actúa como esa persona hoy.',extra:'Escribe: «La versión de mí que ya logró [meta] es alguien que…» · lista 5 comportamientos · elige 1 y practícalo hoy como si ya fueras esa persona. La identidad precede a los resultados.'},
      {icon:'🔮',num:'Práctica 15',title:'Autohipnosis ligera',desc:'Induce un estado de relajación profunda y planta una sugestión positiva.',extra:'Siéntate · fija la mirada en un punto arriba de tu línea de visión · cuenta de 10 a 1 relajando cada parte del cuerpo · al llegar a 1, repite tu sugestión 5 veces: «Cada día soy más [cualidad deseada]» · cuenta de 1 a 5 para salir.'},
      {icon:'⚓',num:'Práctica 16',title:'Anclaje de estados positivos',desc:'Asocia un gesto físico con un estado emocional poderoso para activarlo a voluntad.',extra:'Recuerda un momento de máxima confianza · revívelo con todos los sentidos · en el pico de la emoción, presiona pulgar e índice · repite 5 veces. Después, al presionar esos dedos, el estado regresa. Refuerza el ancla diariamente.'},
      {icon:'🧹',num:'Práctica 17',title:'Detox mental',desc:'Durante 24 horas, elimina quejas, críticas y pensamientos negativos conscientes.',extra:'Usa una pulsera o anillo como recordatorio · cada vez que te quejes o critiques, cámbiala de mano · el objetivo: completar 24 horas sin cambiarla. Esto entrena al subconsciente a buscar lo positivo automáticamente.'},
      {icon:'👀',num:'Práctica 18',title:'Observación de pensamientos',desc:'Durante 10 minutos, observa tus pensamientos sin juzgarlos ni seguirlos.',extra:'Siéntate en silencio · imagina que tus pensamientos son nubes que pasan · no te subas a ninguna · solo observa: «Ahí va un pensamiento de miedo… ahí va uno de trabajo…» · esto crea distancia entre tú y tu programación automática.'},
      {icon:'🔄',num:'Práctica 19',title:'Reencuadre cognitivo',desc:'Toma un problema actual y encuentra 3 formas de verlo como oportunidad.',extra:'Escribe el problema · debajo escribe: «Esto es bueno porque…» y completa 3 veces · ejemplo: «Perdí el empleo» → «Puedo reinventarme / tengo tiempo para mi proyecto / aprendo a confiar en mí.» Tu subconsciente adopta el marco que más repites.'},
      {icon:'🎯',num:'Práctica 20',title:'Decreto de intención',desc:'Escribe una declaración de intención en presente y léela con autoridad 3 veces al día.',extra:'Formato: «Yo, [nombre], decreto que [meta en presente]. Esto es un hecho consumado en mi mente y se manifiesta en mi realidad.» · firmar y fechar · leerla al despertar, al mediodía y antes de dormir con voz firme.'},
      {icon:'🧠',num:'Práctica 21',title:'Reprogramación con repetición',desc:'Elige una frase de poder y escríbela 55 veces durante 5 días consecutivos.',extra:'La técnica 55x5: elige una afirmación corta · escríbela a mano 55 veces cada día por 5 días · no faltes ningún día · la repetición masiva satura el subconsciente y fuerza la aceptación de la nueva creencia.'},
      {icon:'🎵',num:'Práctica 22',title:'Inmersión auditiva subconsciente',desc:'Escucha afirmaciones grabadas en tu propia voz durante 20 minutos.',extra:'Graba 10 afirmaciones en tu voz · escúchalas con audífonos mientras descansas o antes de dormir · tu subconsciente responde mejor a tu propia voz que a la de otros · hazlo mínimo 21 días para resultados profundos.'},
      {icon:'✂️',num:'Práctica 23',title:'Corte de patrón',desc:'Cuando detectes un pensamiento limitante, interrumpe el patrón con una acción física.',extra:'Al notar el pensamiento negativo: aplaude fuerte, di «¡Cancelado!» o ponte de pie · inmediatamente reemplázalo con el pensamiento opuesto · el cerebro asocia la interrupción con el rechazo del patrón viejo. Repite hasta que sea automático.'},
      {icon:'🌊',num:'Práctica 24',title:'Respiración de coherencia',desc:'Practica 5 minutos de respiración rítmica para sincronizar mente y corazón.',extra:'Inhala 5 segundos · exhala 5 segundos · mientras respiras, enfoca la atención en el centro del pecho · piensa en algo que agradeces · este estado de coherencia cardíaca abre el subconsciente a nuevas programaciones.'},
      {icon:'📸',num:'Práctica 25',title:'Tablero de visión mental',desc:'Crea un tablero de visión interno: visualiza 5 imágenes de tu vida ideal en secuencia.',extra:'Cierra los ojos · pasa por 5 escenas como diapositivas: tu casa ideal, tu trabajo, tu salud, tus relaciones, tu cuenta bancaria · quédate 1 minuto en cada una · siente la emoción · hazlo diario al despertar.'},
      {icon:'🗣️',num:'Práctica 26',title:'Técnica del diálogo con el subconsciente',desc:'Escribe una carta a tu subconsciente pidiéndole solución a un problema específico.',extra:'Escribe: «Querido subconsciente, necesito tu ayuda con [problema]. Confío en que mientras duermo encontrarás la mejor solución.» · léela antes de dormir · al despertar, escribe lo primero que venga a tu mente sin filtrar. Las respuestas llegan.'},
      {icon:'🌀',num:'Práctica 27',title:'Limpieza de memoria emocional',desc:'Revive un recuerdo doloroso, cambia su final mentalmente y reemplaza la emoción.',extra:'Elige un recuerdo que aún te afecte · revívelo hasta el punto de dolor · ahora cambia el final: imagina que respondiste con poder, que todo salió bien · repite el nuevo final 5 veces · tu subconsciente no distingue recuerdo real de editado.'},
      {icon:'⏰',num:'Práctica 28',title:'Ritual de los primeros 10 minutos',desc:'Dedica los primeros 10 minutos del día exclusivamente a programar tu mente.',extra:'Al despertar, NO toques el teléfono · 3 min de respiración profunda · 3 min de afirmaciones en voz alta · 4 min de visualización de tu día ideal · estos 10 minutos definen la frecuencia mental de las próximas 14 horas.'},
      {icon:'🔑',num:'Práctica 29',title:'Pregunta generativa antes de dormir',desc:'Hazte una pregunta poderosa justo antes de dormir y deja que el subconsciente trabaje.',extra:'Ejemplos: «¿Cuál es la mejor manera de duplicar mis ingresos?» «¿Qué necesito soltar para avanzar?» · no busques la respuesta conscientemente · solo planta la pregunta y duerme · las ideas llegarán en días como intuición o claridad repentina.'},
      {icon:'🏆',num:'Práctica 30',title:'Celebración anticipada',desc:'Celebra tu meta como si ya se hubiera cumplido: siente la alegría ahora.',extra:'Ponte de pie · sonríe · di en voz alta: «¡Lo logré! [describe tu meta cumplida]» · aplaude, salta, ríe · mantén la emoción 2 minutos mínimo · el subconsciente no distingue entre alegría real y generada: ambas programan éxito.'}
    ],
    affs: [
      'Mi mente subconsciente trabaja a mi favor las 24 horas del día.',
      'Cada pensamiento positivo que elijo reprograma mi realidad.',
      'Mi subconsciente acepta y materializa todo lo que repito con fe.',
      'Soy el programador de mi mente y elijo instalar creencias poderosas.',
      'Mi mente es un imán que atrae exactamente lo que visualizo con emoción.',
      'Cada día mi diálogo interno es más positivo, más fuerte, más claro.',
      'Mis creencias limitantes se disuelven y son reemplazadas por verdades que me empoderan.',
      'Mientras duermo, mi subconsciente resuelve problemas y crea oportunidades.',
      'Tengo el poder de cambiar cualquier patrón mental que no me sirva.',
      'Mi visualización es tan poderosa que mi cerebro la acepta como realidad.',
      'Elijo pensamientos que me elevan y rechazo los que me limitan.',
      'Mi mente subconsciente es mi aliada más poderosa en cada proyecto.',
      'Reprogramo mi mente con la misma facilidad con la que respiro.',
      'Cada afirmación que repito se graba más profundo en mi subconsciente.',
      'Mi identidad se expande cada día para contener mis metas más grandes.',
      'Confío en la inteligencia infinita de mi mente subconsciente.',
      'Lo que imagino con detalle y emoción se convierte en mi experiencia.',
      'Mi mente trabaja en silencio para manifestar mis intenciones más claras.',
      'Suelto el miedo y permito que mi subconsciente me guíe hacia lo mejor.',
      'Cada noche planto semillas de éxito en mi mente y cada día las veo crecer.',
      'Mi diálogo interno es el de una persona exitosa, segura y abundante.',
      'Mis pensamientos crean mi realidad y hoy elijo pensar en grande.',
      'El poder de mi mente supera cualquier obstáculo externo.',
      'Estoy conectado con la sabiduría profunda de mi subconsciente.',
      'Mi mente subconsciente conoce el camino y yo confío en su guía.',
      'Cada respiración consciente profundiza mi conexión con mi poder interior.',
      'Transformo miedos en combustible para mi crecimiento personal.',
      'Mi mente es fértil y todo lo que siembro con repetición florece.',
      'Vivo en coherencia entre lo que pienso, siento y hago.',
      'Soy el arquitecto de mi destino y mi mente es la herramienta más poderosa que tengo.'
    ],
    leyes: [
      {title:'Ley de la repetición',idea:'Lo que repites con emoción, tu subconsciente lo acepta como verdad.',ej:'Una afirmación dicha 100 veces con fe se vuelve creencia. Una dicha sin sentir, se pierde.'},
      {title:'Ley de la sugestión dominante',idea:'Tu subconsciente obedece la idea que más se repite, no la más lógica.',ej:'Si te dices «no puedo» 50 veces al día y «soy capaz» una vez, gana el «no puedo».'},
      {title:'Ley de la emoción',idea:'El subconsciente no procesa palabras, procesa emociones.',ej:'Visualizar tu meta sintiéndola ya lograda es 100 veces más potente que solo pensarla.'},
      {title:'Ley del espejo',idea:'Tu realidad externa es un reflejo exacto de tu programación interna.',ej:'Si crees que el dinero es difícil, tu vida lo confirmará. Cambia la creencia y cambia el reflejo.'},
      {title:'Ley de la sustitución',idea:'No puedes borrar un pensamiento negativo, solo puedes reemplazarlo.',ej:'En lugar de luchar contra «soy un fracaso», instala «estoy en constante crecimiento».'},
      {title:'Ley de la relajación',idea:'El subconsciente es más receptivo cuando la mente consciente se relaja.',ej:'Las afirmaciones antes de dormir o en meditación penetran más profundo que las dichas con estrés.'},
      {title:'Ley de la expectativa',idea:'Tu subconsciente materializa lo que genuinamente esperas, no lo que deseas.',ej:'Desear riqueza pero esperar pobreza produce pobreza. Alinea tu expectativa con tu deseo.'},
      {title:'Ley de la correspondencia',idea:'Tu mundo exterior siempre corresponde a tu mundo interior.',ej:'Personas exitosas no tienen menos problemas — tienen una programación interna que los convierte en oportunidades.'},
      {title:'Ley del mínimo esfuerzo subconsciente',idea:'El subconsciente siempre elige el camino de menor resistencia entre tus programas instalados.',ej:'Si tienes instalado «trabajar duro = éxito», rechazarás oportunidades fáciles. Actualiza el programa.'},
      {title:'Ley de la impresión final',idea:'El último pensamiento antes de dormir tiene el mayor impacto en tu programación nocturna.',ej:'Dormirte preocupado programa 8 horas de ansiedad subconsciente. Dormirte agradecido programa 8 horas de soluciones.'},
      {title:'Ley de la coherencia interna',idea:'Cuando pensamiento, emoción y acción están alineados, el subconsciente multiplica los resultados.',ej:'Afirmar abundancia, sentir escasez y actuar con miedo produce cero. La coherencia es el multiplicador.'},
      {title:'Ley de la identidad',idea:'Tu subconsciente protege tu identidad actual — solo cambias cuando cambias quién crees ser.',ej:'No basta con querer ser rico; debes creer «yo soy alguien que genera riqueza». El subconsciente defiende la identidad, no la meta.'}
    ]
  },
  en: {
    practices: [
      {icon:'🌅',num:'Practice 01',title:'Daily affirmation',desc:'Repeat an affirmation 5 times today, out loud, feeling every word.',extra:'Your affirmation today: "My mind works in my favor. What I think today, I live tomorrow."'},
      {icon:'👁️',num:'Practice 02',title:'Guided visualization',desc:'Close your eyes for 5 minutes and vividly experience the version of you that already achieved your dream.',extra:'Take 3 deep breaths · imagine a specific scene (where, what you wear, who is there) · feel the emotion of having already achieved it · stay there for 5 minutes.'},
      {icon:'📓',num:'Practice 03',title:'Thought journal',desc:'At the end of the day, write down 3 thoughts you had and classify them.',extra:'Thought 1, 2, and 3 → did it push me forward or hold me back? What you repeat without noticing becomes your reality.'},
      {icon:'🔍',num:'Practice 04',title:'Belief audit',desc:'Identify 3 beliefs you repeat about yourself and evaluate whether they serve you.',extra:'Write: "I am…", "I can\'t…", "Life is…" → for each one ask: who taught me this? Is it absolutely true? Does it bring me closer to my goal? If it doesn\'t serve you, rewrite it with a version that does.'},
      {icon:'💬',num:'Practice 05',title:'Inner dialogue rewrite',desc:'Detect one negative phrase you tell yourself today and transform it into its constructive opposite.',extra:'Example: "I\'m not enough" → "I\'m constantly growing and every day I become more capable." Repeat the new version 10 times out loud with conviction. Write it somewhere visible.'},
      {icon:'😨',num:'Practice 06',title:'Fear inventory',desc:'Make a list of 5 current fears and ask yourself what would happen if they didn\'t exist.',extra:'Write each fear · below write: "If this fear didn\'t exist, I would…" · choose one and take the smallest action today to overcome it. The subconscious respects action, not intention.'},
      {icon:'🙏',num:'Practice 07',title:'Gratitude rewiring',desc:'Write 5 things you\'re grateful for as if you just received them.',extra:'Use present tense and emotion: "I am deeply grateful for…" · close your eyes and feel each one in your body · gratitude reprograms the subconscious toward abundance in less than 21 days.'},
      {icon:'🎬',num:'Practice 08',title:'Mental rehearsal',desc:'Mentally walk through a future situation experiencing it as if it already had the best outcome.',extra:'Choose an upcoming meeting, interview, or conversation · close your eyes · live it step by step: what you say, how you move, what you feel · repeat 3 times. Your brain can\'t distinguish lived experience from rehearsed experience.'},
      {icon:'🪞',num:'Practice 09',title:'Mirror technique',desc:'Look into your own eyes in the mirror and repeat identity affirmations for 3 minutes.',extra:'Stand up, direct gaze into your eyes · repeat: "I am powerful. I deserve the best. My mind creates my reality." · don\'t break eye contact · if you feel discomfort, it\'s a sign your subconscious is processing the change.'},
      {icon:'📝',num:'Practice 10',title:'Future scripting',desc:'Write in present tense with detail a complete day of your ideal life 3 years from now.',extra:'Include: what time you wake up, where you live, what you eat for breakfast, who you talk to, what work you do, how much you earn, how you feel going to sleep · read it every night before bed for 7 days.'},
      {icon:'🌙',num:'Practice 11',title:'Pre-sleep programming',desc:'In the last 5 minutes before sleep, repeat a clear command to your subconscious.',extra:'Lying down, relaxed, eyes closed · mentally repeat: "While I sleep, my subconscious works on [your specific goal]" · visualize the final result · let go and sleep. The hypnagogic state is the direct window to the subconscious.'},
      {icon:'🧘',num:'Practice 12',title:'Theta state meditation',desc:'Meditate for 10 minutes focusing only on breathing to reach theta brainwaves.',extra:'Sit comfortably · breathe 4-7-8 (inhale 4s, hold 7s, exhale 8s) · don\'t try to empty your mind, just observe · at 7-10 minutes you enter theta: here your affirmations penetrate 100 times deeper.'},
      {icon:'🚫',num:'Practice 13',title:'Limiting belief elimination',desc:'Choose one limiting belief and apply the 4-step protocol to dismantle it.',extra:'1) Write the belief · 2) Find 3 pieces of evidence that it\'s NOT true · 3) Write the opposite empowering belief · 4) Repeat the new belief for 21 days, morning and night. The subconscious accepts what is repeated with emotion.'},
      {icon:'🦋',num:'Practice 14',title:'Identity shift',desc:'Define who you need to BE (not just do) to achieve your goal and act as that person today.',extra:'Write: "The version of me that already achieved [goal] is someone who…" · list 5 behaviors · choose 1 and practice it today as if you were already that person. Identity precedes results.'},
      {icon:'🔮',num:'Practice 15',title:'Light self-hypnosis',desc:'Induce a state of deep relaxation and plant a positive suggestion.',extra:'Sit down · fix your gaze on a point above your line of sight · count from 10 to 1 relaxing each body part · at 1, repeat your suggestion 5 times: "Every day I am more [desired quality]" · count from 1 to 5 to come out.'},
      {icon:'⚓',num:'Practice 16',title:'Positive state anchoring',desc:'Associate a physical gesture with a powerful emotional state to activate it at will.',extra:'Remember a moment of peak confidence · relive it with all senses · at the peak of the emotion, press thumb and index finger together · repeat 5 times. Afterward, pressing those fingers brings the state back. Reinforce the anchor daily.'},
      {icon:'🧹',num:'Practice 17',title:'Mental detox',desc:'For 24 hours, eliminate complaints, criticism, and conscious negative thoughts.',extra:'Use a bracelet or ring as a reminder · every time you complain or criticize, switch it to the other hand · the goal: complete 24 hours without switching. This trains the subconscious to seek the positive automatically.'},
      {icon:'👀',num:'Practice 18',title:'Thought observation',desc:'For 10 minutes, observe your thoughts without judging or following them.',extra:'Sit in silence · imagine your thoughts are clouds passing by · don\'t ride any of them · just observe: "There goes a fear thought… there goes a work thought…" · this creates distance between you and your automatic programming.'},
      {icon:'🔄',num:'Practice 19',title:'Cognitive reframing',desc:'Take a current problem and find 3 ways to see it as an opportunity.',extra:'Write the problem · below write: "This is good because…" and complete it 3 times · example: "I lost my job" → "I can reinvent myself / I have time for my project / I learn to trust myself." Your subconscious adopts the frame you repeat most.'},
      {icon:'🎯',num:'Practice 20',title:'Intention decree',desc:'Write a declaration of intention in present tense and read it with authority 3 times a day.',extra:'Format: "I, [name], decree that [goal in present tense]. This is an accomplished fact in my mind and manifests in my reality." · sign and date it · read at waking, midday, and before bed with a firm voice.'},
      {icon:'🧠',num:'Practice 21',title:'Repetition reprogramming',desc:'Choose a power phrase and write it 55 times for 5 consecutive days.',extra:'The 55x5 technique: choose a short affirmation · write it by hand 55 times each day for 5 days · don\'t miss a single day · massive repetition saturates the subconscious and forces acceptance of the new belief.'},
      {icon:'🎵',num:'Practice 22',title:'Subconscious audio immersion',desc:'Listen to affirmations recorded in your own voice for 20 minutes.',extra:'Record 10 affirmations in your voice · listen with headphones while resting or before sleep · your subconscious responds better to your own voice than others\' · do it for at least 21 days for deep results.'},
      {icon:'✂️',num:'Practice 23',title:'Pattern interrupt',desc:'When you detect a limiting thought, break the pattern with a physical action.',extra:'When you notice the negative thought: clap hard, say "Cancelled!" or stand up · immediately replace it with the opposite thought · the brain associates the interruption with rejection of the old pattern. Repeat until automatic.'},
      {icon:'🌊',num:'Practice 24',title:'Coherence breathing',desc:'Practice 5 minutes of rhythmic breathing to synchronize mind and heart.',extra:'Inhale 5 seconds · exhale 5 seconds · while breathing, focus attention on the center of your chest · think of something you\'re grateful for · this heart coherence state opens the subconscious to new programming.'},
      {icon:'📸',num:'Practice 25',title:'Mental vision board',desc:'Create an internal vision board: visualize 5 images of your ideal life in sequence.',extra:'Close your eyes · cycle through 5 scenes like slides: your ideal home, your work, your health, your relationships, your bank account · stay 1 minute on each · feel the emotion · do it daily upon waking.'},
      {icon:'🗣️',num:'Practice 26',title:'Subconscious dialogue technique',desc:'Write a letter to your subconscious asking it to solve a specific problem.',extra:'Write: "Dear subconscious, I need your help with [problem]. I trust that while I sleep you will find the best solution." · read it before bed · upon waking, write the first thing that comes to mind without filtering. The answers come.'},
      {icon:'🌀',num:'Practice 27',title:'Emotional memory clearing',desc:'Relive a painful memory, mentally change its ending, and replace the emotion.',extra:'Choose a memory that still affects you · relive it up to the point of pain · now change the ending: imagine you responded with power, that everything turned out well · repeat the new ending 5 times · your subconscious can\'t distinguish real memory from edited memory.'},
      {icon:'⏰',num:'Practice 28',title:'First 10 minutes ritual',desc:'Dedicate the first 10 minutes of the day exclusively to programming your mind.',extra:'Upon waking, do NOT touch your phone · 3 min of deep breathing · 3 min of affirmations out loud · 4 min of visualization of your ideal day · these 10 minutes set the mental frequency for the next 14 hours.'},
      {icon:'🔑',num:'Practice 29',title:'Generative question before sleep',desc:'Ask yourself a powerful question right before sleep and let the subconscious work.',extra:'Examples: "What is the best way to double my income?" "What do I need to let go of to move forward?" · don\'t search for the answer consciously · just plant the question and sleep · ideas will arrive in days as intuition or sudden clarity.'},
      {icon:'🏆',num:'Practice 30',title:'Anticipatory celebration',desc:'Celebrate your goal as if it has already been achieved: feel the joy now.',extra:'Stand up · smile · say out loud: "I did it! [describe your achieved goal]" · clap, jump, laugh · maintain the emotion for at least 2 minutes · the subconscious can\'t distinguish between real and generated joy: both program success.'}
    ],
    affs: [
      'My subconscious mind works in my favor 24 hours a day.',
      'Every positive thought I choose reprograms my reality.',
      'My subconscious accepts and materializes everything I repeat with faith.',
      'I am the programmer of my mind and I choose to install powerful beliefs.',
      'My mind is a magnet that attracts exactly what I visualize with emotion.',
      'Every day my inner dialogue becomes more positive, stronger, clearer.',
      'My limiting beliefs dissolve and are replaced by truths that empower me.',
      'While I sleep, my subconscious solves problems and creates opportunities.',
      'I have the power to change any mental pattern that no longer serves me.',
      'My visualization is so powerful that my brain accepts it as reality.',
      'I choose thoughts that elevate me and reject those that limit me.',
      'My subconscious mind is my most powerful ally in every project.',
      'I reprogram my mind with the same ease that I breathe.',
      'Every affirmation I repeat is engraved deeper into my subconscious.',
      'My identity expands every day to contain my biggest goals.',
      'I trust the infinite intelligence of my subconscious mind.',
      'What I imagine with detail and emotion becomes my experience.',
      'My mind works silently to manifest my clearest intentions.',
      'I release fear and allow my subconscious to guide me toward the best.',
      'Every night I plant seeds of success in my mind and every day I watch them grow.',
      'My inner dialogue is that of a successful, confident, and abundant person.',
      'My thoughts create my reality and today I choose to think big.',
      'The power of my mind surpasses any external obstacle.',
      'I am connected with the deep wisdom of my subconscious.',
      'My subconscious mind knows the way and I trust its guidance.',
      'Every conscious breath deepens my connection to my inner power.',
      'I transform fears into fuel for my personal growth.',
      'My mind is fertile and everything I sow with repetition blossoms.',
      'I live in coherence between what I think, feel, and do.',
      'I am the architect of my destiny and my mind is the most powerful tool I have.'
    ],
    leyes: [
      {title:'Law of repetition',idea:'What you repeat with emotion, your subconscious accepts as truth.',ej:'An affirmation said 100 times with faith becomes a belief. One said without feeling is lost.'},
      {title:'Law of dominant suggestion',idea:'Your subconscious obeys the idea that is repeated most, not the most logical one.',ej:'If you tell yourself "I can\'t" 50 times a day and "I can" once, "I can\'t" wins.'},
      {title:'Law of emotion',idea:'The subconscious doesn\'t process words — it processes emotions.',ej:'Visualizing your goal while feeling it already achieved is 100 times more potent than just thinking about it.'},
      {title:'Law of the mirror',idea:'Your external reality is an exact reflection of your internal programming.',ej:'If you believe money is hard, your life will confirm it. Change the belief and change the reflection.'},
      {title:'Law of substitution',idea:'You cannot erase a negative thought — you can only replace it.',ej:'Instead of fighting "I\'m a failure," install "I\'m in constant growth."'},
      {title:'Law of relaxation',idea:'The subconscious is most receptive when the conscious mind relaxes.',ej:'Affirmations before sleep or in meditation penetrate deeper than those said under stress.'},
      {title:'Law of expectation',idea:'Your subconscious materializes what you genuinely expect, not what you wish for.',ej:'Wishing for wealth but expecting poverty produces poverty. Align your expectation with your desire.'},
      {title:'Law of correspondence',idea:'Your outer world always corresponds to your inner world.',ej:'Successful people don\'t have fewer problems — they have internal programming that turns them into opportunities.'},
      {title:'Law of subconscious least effort',idea:'The subconscious always chooses the path of least resistance among your installed programs.',ej:'If you have "hard work = success" installed, you\'ll reject easy opportunities. Update the program.'},
      {title:'Law of final impression',idea:'The last thought before sleep has the greatest impact on your overnight programming.',ej:'Falling asleep worried programs 8 hours of subconscious anxiety. Falling asleep grateful programs 8 hours of solutions.'},
      {title:'Law of internal coherence',idea:'When thought, emotion, and action are aligned, the subconscious multiplies results.',ej:'Affirming abundance, feeling scarcity, and acting from fear produces zero. Coherence is the multiplier.'},
      {title:'Law of identity',idea:'Your subconscious protects your current identity — you only change when you change who you believe you are.',ej:'It\'s not enough to want to be rich; you must believe "I am someone who generates wealth." The subconscious defends identity, not goals.'}
    ]
  }
};
